# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76283c4e76be5fc3f966fb0d019d1d1e1024cb7315a747e888a579655345a33f9d7e9bd462c354c7a2f6aa1bfd19ad4731adc4938b4fee4e5d07599601e38888

test:
  secret_key_base: 237c5196db3026cf82c4252d0688ec4325caa804a38b1e300af2ec9d8f13b692b864119bb48f4931fe5d742581fe872be1cd3c925feab0d62cd7b04db0c85bc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
